In [5]:
import numpy as np
import pandas as pd

# PS 01
David Gao
## 1  Basic Python
### 1.1 Lists
#### 1.

In [2]:
movies = ['spider man', 'super man', 'bat man', 'pacific rim', 'titanic', 'avengers']
movies

['spider man', 'super man', 'bat man', 'pacific rim', 'titanic', 'avengers']

#### 2.

In [3]:
movies13 = movies[:3]
movies13

['spider man', 'super man', 'bat man']

#### 3.

In [4]:
movies_result = movies[:2] + movies[4:]
movies_result

['spider man', 'super man', 'titanic', 'avengers']

### 1.2 Loops
#### 1.

In [5]:
numbers = []
for i in range(10):
    numbers.append(70 + i)

numbers

[70, 71, 72, 73, 74, 75, 76, 77, 78, 79]

#### 2.

In [7]:
sum = 0
for i in range(101):
    sum = sum + i

sum

5050

#### 3.

In [2]:
people = ['Adam', 'Ashin', 'Inukai', 'Ikki']
seats = ['33', '12', '45', '2', '17']
for i in range(len(people)):
    print(people[i] + ': ' + seats[i])

Adam: 33
Ashin: 12
Inukai: 45
Ikki: 2


### 1.3 Comprehensions
#### 1.

In [12]:
squares = [(i + 1)*(i + 1) for i in range(10)]
squares

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

#### 2.

In [13]:
index = {(i + 1):squares[i] for i in range(10)}
index

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

### 1.4 Functions and data transformations
#### 1.

In [3]:
def convert_time( x ):
    hours = (x - x%100)/100
    min = x%100/60
    return hours + min

convert_time(1015)

10.25

## 2 Numpy and Pandas
### 2.1 Series
#### 1.

In [4]:
numbers = np.arange(10) + 1
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
squares = numbers**2
squares

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### 2.

In [7]:
combine = pd.Series(squares, index = numbers)
combine

1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81
10    100
dtype: int32

#### 3.

In [10]:
extract = combine[combine.index%3 == 0]
extract

3     9
6    36
9    81
dtype: int32

#### 4.

In [13]:
result = extract.to_numpy()
result

array([ 9, 36, 81])

#### 5.

In [10]:
randoms = np.random.randint(low = 1, high = 10, size = 10)
randoms

array([2, 8, 8, 5, 6, 1, 6, 9, 5, 3])

Reference: [random number generator](https://datatofish.com/random-integers-pandas-dataframe/)

In [11]:
square_roots = pd.Series(randoms, index = [(i + 1) for i in range(10)])
square_roots

1     2
2     8
3     8
4     5
5     6
6     1
7     6
8     9
9     5
10    3
dtype: int32

In [15]:
for i in square_roots.index - 1:
    square_roots[i + 1] = np.sqrt(square_roots.index[i])
square_roots

1     1.000000
2     1.414214
3     1.732051
4     2.000000
5     2.236068
6     2.449490
7     2.645751
8     2.828427
9     3.000000
10    3.162278
dtype: float64

### 2.2 Data Frames
#### 1.

In [20]:
df = pd.DataFrame({'square':[(i+1)*(i+1) for i in range(10)], 'sqrt':[np.sqrt(i+1) for i in range(10)]}, index = [i+1 for i in range(10)])
df

square      sqrt
1        1  1.000000
2        4  1.414214
3        9  1.732051
4       16  2.000000
5       25  2.236068
6       36  2.449490
7       49  2.645751
8       64  2.828427
9       81  3.000000
10     100  3.162278

#### 2.

In [22]:
df["log"] = [np.log(i) for i in df.index]
df

square      sqrt       log
1        1  1.000000  0.000000
2        4  1.414214  0.693147
3        9  1.732051  1.098612
4       16  2.000000  1.386294
5       25  2.236068  1.609438
6       36  2.449490  1.791759
7       49  2.645751  1.945910
8       64  2.828427  2.079442
9       81  3.000000  2.197225
10     100  3.162278  2.302585

#### 3.

In [26]:
result = df[df.sqrt >= 2.0]
result = result[result.log < 2.0]
result

square      sqrt       log
4      16  2.000000  1.386294
5      25  2.236068  1.609438
6      36  2.449490  1.791759
7      49  2.645751  1.945910

#### 4.

In [27]:
df["int_value"] = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten']
df

square      sqrt       log int_value
1        1  1.000000  0.000000       one
2        4  1.414214  0.693147       two
3        9  1.732051  1.098612     three
4       16  2.000000  1.386294      four
5       25  2.236068  1.609438      five
6       36  2.449490  1.791759       six
7       49  2.645751  1.945910     seven
8       64  2.828427  2.079442     eight
9       81  3.000000  2.197225      nine
10     100  3.162278  2.302585       ten

#### 5.

In [28]:
df["int_value"] = df["int_value"].str.capitalize()
df

square      sqrt       log int_value
1        1  1.000000  0.000000       One
2        4  1.414214  0.693147       Two
3        9  1.732051  1.098612     Three
4       16  2.000000  1.386294      Four
5       25  2.236068  1.609438      Five
6       36  2.449490  1.791759       Six
7       49  2.645751  1.945910     Seven
8       64  2.828427  2.079442     Eight
9       81  3.000000  2.197225      Nine
10     100  3.162278  2.302585       Ten

Reference: [First letter capitalize](https://www.geeksforgeeks.org/python-pandas-series-str-capitalize/#:~:text=We%20are%20using%20the%20pandas%20Series.str.capitalize%20%28%29%20method,%5B%27Name%27%5D.head%20%28%29%29%20print%28g.str.lower%20%28%29%2C%20end%20%3D%27nn%27%29%20print%28g.str.capitalize%20%28%29%29)

## 3 Explore Data
### 1.

In [6]:
gapminder = pd.read_csv(r'gapminder.csv', sep='\t')
gapminder.head(3)

iso3   name iso2    region                       sub-region  \
0  ABW  Aruba   AW  Americas  Latin America and the Caribbean   
1  ABW  Aruba   AW  Americas  Latin America and the Caribbean   
2  ABW  Aruba   AW  Americas  Latin America and the Caribbean   

  intermediate-region    time  totalPopulation  fertilityRate  lifeExpectancy  \
0           Caribbean  1960.0          54211.0          4.820          65.662   
1           Caribbean  1961.0          55438.0          4.655          66.074   
2           Caribbean  1962.0          56225.0          4.471          66.444   

   ...  accessElectricity  agriculturalLand  agricultureTractors  \
0  ...                NaN               NaN                  NaN   
1  ...                NaN              20.0                  NaN   
2  ...                NaN              20.0                  NaN   

   cerealProduction  fertilizerHa        co2  greenhouseGases     co2_PC  \
0               NaN           NaN  11092.675              NaN  204.62037   
1               NaN           NaN  11576.719              NaN  208.82281   
2               NaN           NaN  12713.489              NaN  226.11808   

   pm2.5_35  battleDeaths  
0       NaN           NaN  
1       NaN           NaN  
2       NaN           NaN  

[3 rows x 25 columns]

#### 2.
##### (a)

In [11]:
rows,columns = gapminder.shape
columns

25

##### (b)

In [12]:
rows

13055

##### (c)

In [7]:
gapminder.head(5)

iso3   name iso2    region                       sub-region  \
0  ABW  Aruba   AW  Americas  Latin America and the Caribbean   
1  ABW  Aruba   AW  Americas  Latin America and the Caribbean   
2  ABW  Aruba   AW  Americas  Latin America and the Caribbean   
3  ABW  Aruba   AW  Americas  Latin America and the Caribbean   
4  ABW  Aruba   AW  Americas  Latin America and the Caribbean   

  intermediate-region    time  totalPopulation  fertilityRate  lifeExpectancy  \
0           Caribbean  1960.0          54211.0          4.820          65.662   
1           Caribbean  1961.0          55438.0          4.655          66.074   
2           Caribbean  1962.0          56225.0          4.471          66.444   
3           Caribbean  1963.0          56695.0          4.271          66.787   
4           Caribbean  1964.0          57032.0          4.059          67.113   

   ...  accessElectricity  agriculturalLand  agricultureTractors  \
0  ...                NaN               NaN                  NaN   
1  ...                NaN              20.0                  NaN   
2  ...                NaN              20.0                  NaN   
3  ...                NaN              20.0                  NaN   
4  ...                NaN              20.0                  NaN   

   cerealProduction  fertilizerHa        co2  greenhouseGases     co2_PC  \
0               NaN           NaN  11092.675              NaN  204.62037   
1               NaN           NaN  11576.719              NaN  208.82281   
2               NaN           NaN  12713.489              NaN  226.11808   
3               NaN           NaN  12178.107              NaN  214.80037   
4               NaN           NaN  11840.743              NaN  207.61578   

   pm2.5_35  battleDeaths  
0       NaN           NaN  
1       NaN           NaN  
2       NaN           NaN  
3       NaN           NaN  
4       NaN           NaN  

[5 rows x 25 columns]

The data looks reasonable.

#### 3.

In [14]:
Ukrainian = gapminder[gapminder.name == "Ukraine"]
Ukrainian = Ukrainian[["iso2", "totalPopulation", "cerealProduction", "time"]]
Ukrainian.head(5)

iso2  totalPopulation  cerealProduction    time
12152   UA       42664652.0               NaN  1960.0
12153   UA       43206345.0               NaN  1961.0
12154   UA       43752230.0               NaN  1962.0
12155   UA       44288608.0               NaN  1963.0
12156   UA       44796964.0               NaN  1964.0

In [16]:
rows,columns = Ukrainian.shape
rows

60

I get 60 cases.

#### 4.

In [17]:
Ukrainian = Ukrainian.rename({"time": "year"}, axis = 1)
Ukrainian.head(5)

iso2  totalPopulation  cerealProduction    year
12152   UA       42664652.0               NaN  1960.0
12153   UA       43206345.0               NaN  1961.0
12154   UA       43752230.0               NaN  1962.0
12155   UA       44288608.0               NaN  1963.0
12156   UA       44796964.0               NaN  1964.0

Reference: [Change column name](https://www.w3schools.com/python/pandas/ref_df_rename.asp)

I spent around 4 hours on this PS.