In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1 Basic Python
# 1.1 Lists
# 1
movies = ['spider man', 'super man', 'bat man', 'pacific rim', 'titanic', 'avengers']
movies

['spider man', 'super man', 'bat man', 'pacific rim', 'titanic', 'avengers']

In [3]:
# 2
movies13 = movies[:3]
movies13

['spider man', 'super man', 'bat man']

In [4]:
# 3
movies_result = movies[:2] + movies[4:]
movies_result

['spider man', 'super man', 'titanic', 'avengers']

In [6]:
# 1.2 Loops
# 1
numbers = []
for i in range(10):
    numbers.append(70 + i)

numbers

[70, 71, 72, 73, 74, 75, 76, 77, 78, 79]

In [7]:
# 2
sum = 0
for i in range(101):
    sum = sum + i

sum

5050

In [9]:
# 3
people = ['Adam', 'Ashin', 'Inukai', 'Ikki']
seats = ['33', '12', '45', '2', '17']
for i in range(len(people)):
    print(people[i] + ': ' + seats[i])

Adam: 33
Ashin: 12
Inukai: 45
Ikki: 2


In [12]:
# 1.3
# 1
squares = [(i + 1)*(i + 1) for i in range(10)]
squares

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [13]:
index = {(i + 1):squares[i] for i in range(10)}
index

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [18]:
def convert_time( x ):
    hours = (x - x%100)/100
    min = x%100/60
    # print(hours + min)

    return hours + min

convert_time(1015)

10.25

In [4]:
# 2 Numpy and Pandas
# 2.1 Series
# 1
numbers = np.arange(10) + 1
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
squares = numbers**2
squares

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
# 2
combine = pd.Series(squares, index = numbers)
combine

1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81
10    100
dtype: int32

In [10]:
# 3
extract = combine[combine.index%3 == 0]
extract

3     9
6    36
9    81
dtype: int32

In [13]:
# 4 Question
result = extract.to_numpy()
result

array([ 9, 36, 81])

In [10]:
# 5
randoms = np.random.randint(low = 1, high = 10, size = 10)
randoms

array([2, 8, 8, 5, 6, 1, 6, 9, 5, 3])

In [11]:
square_roots = pd.Series(randoms, index = [(i + 1) for i in range(10)])
square_roots

1     2
2     8
3     8
4     5
5     6
6     1
7     6
8     9
9     5
10    3
dtype: int32

In [15]:
for i in square_roots.index - 1:
    square_roots[i + 1] = np.sqrt(square_roots.index[i])
square_roots

1     1.000000
2     1.414214
3     1.732051
4     2.000000
5     2.236068
6     2.449490
7     2.645751
8     2.828427
9     3.000000
10    3.162278
dtype: float64

In [20]:
# 2.2 Data Frames
# 1
df = pd.DataFrame({'square':[(i+1)*(i+1) for i in range(10)], 'sqrt':[np.sqrt(i+1) for i in range(10)]}, index = [i+1 for i in range(10)])
df

square      sqrt
1        1  1.000000
2        4  1.414214
3        9  1.732051
4       16  2.000000
5       25  2.236068
6       36  2.449490
7       49  2.645751
8       64  2.828427
9       81  3.000000
10     100  3.162278

In [22]:
# 2
df["log"] = [np.log(i) for i in df.index]
df

square      sqrt       log
1        1  1.000000  0.000000
2        4  1.414214  0.693147
3        9  1.732051  1.098612
4       16  2.000000  1.386294
5       25  2.236068  1.609438
6       36  2.449490  1.791759
7       49  2.645751  1.945910
8       64  2.828427  2.079442
9       81  3.000000  2.197225
10     100  3.162278  2.302585

In [26]:
# 3
result = df[df.sqrt >= 2.0]
result = result[result.log < 2.0]
result

square      sqrt       log
4      16  2.000000  1.386294
5      25  2.236068  1.609438
6      36  2.449490  1.791759
7      49  2.645751  1.945910

In [27]:
# 4
df["int_value"] = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten']
df

square      sqrt       log int_value
1        1  1.000000  0.000000       one
2        4  1.414214  0.693147       two
3        9  1.732051  1.098612     three
4       16  2.000000  1.386294      four
5       25  2.236068  1.609438      five
6       36  2.449490  1.791759       six
7       49  2.645751  1.945910     seven
8       64  2.828427  2.079442     eight
9       81  3.000000  2.197225      nine
10     100  3.162278  2.302585       ten

In [28]:
# 5
df["int_value"] = df["int_value"].str.capitalize()
df

square      sqrt       log int_value
1        1  1.000000  0.000000       One
2        4  1.414214  0.693147       Two
3        9  1.732051  1.098612     Three
4       16  2.000000  1.386294      Four
5       25  2.236068  1.609438      Five
6       36  2.449490  1.791759       Six
7       49  2.645751  1.945910     Seven
8       64  2.828427  2.079442     Eight
9       81  3.000000  2.197225      Nine
10     100  3.162278  2.302585       Ten

In [46]:
# 3 Explore Data
# 1
gapminder = pd.read_csv(r'C:\UW\SPR 2022\INFO 370\gapminder.csv', sep='\t')

In [50]:
# 2
# (a)
rows,columns = gapminder.shape
columns

25

In [51]:
# (b)
rows

13055

In [53]:
# (c)
gapminder.sample(5)

iso3                              name iso2  region          sub-region  \
6486   LAO  Lao People's Democratic Republic   LA    Asia  South-eastern Asia   
10709  SRB                            Serbia   RS  Europe     Southern Europe   
1269   BIH            Bosnia and Herzegovina   BA  Europe     Southern Europe   
4187   GEO                           Georgia   GE    Asia        Western Asia   
10007  RUS                Russian Federation   RU  Europe      Eastern Europe   

      intermediate-region    time  totalPopulation  fertilityRate  \
6486                  NaN  2006.0        5846074.0          3.516   
10709                 NaN  2019.0        6945235.0          1.520   
1269                  NaN  1964.0        3478997.0          3.515   
4187                  NaN  1994.0        4836076.0          1.946   
10007                 NaN  1981.0      139941000.0          1.910   

       lifeExpectancy  ...  accessElectricity  agriculturalLand  \
6486         62.18200  ...           57.04106           20250.0   
10709        75.68537  ...           99.80000               NaN   
1269         62.81800  ...                NaN               NaN   
4187         69.84900  ...                NaN           30970.0   
10007        67.26390  ...                NaN               NaN   

       agricultureTractors  cerealProduction  fertilizerHa          co2  \
6486                   NaN         3113650.0           NaN     1796.830   
10709                  NaN               NaN           NaN          NaN   
1269                   NaN               NaN           NaN          NaN   
4187               18200.0          470638.0      38.99371     6083.553   
10007                  NaN               NaN           NaN  3425062.341   

       greenhouseGases    co2_PC  pm2.5_35  battleDeaths  
6486      2.507337e+04   0.30736       NaN           NaN  
10709              NaN       NaN       NaN           NaN  
1269               NaN       NaN       NaN           NaN  
4187      1.649298e+04   1.25795       NaN           NaN  
10007     3.032440e+06  24.47505       NaN           NaN  

[5 rows x 25 columns]

In [60]:
# 3
Ukrainian = gapminder[gapminder.name == "Ukraine"]
Ukrainian = Ukrainian[["iso2", "totalPopulation", "cerealProduction", "time"]]
Ukrainian.head(10)

iso2  totalPopulation  cerealProduction    time
12152   UA       42664652.0               NaN  1960.0
12153   UA       43206345.0               NaN  1961.0
12154   UA       43752230.0               NaN  1962.0
12155   UA       44288608.0               NaN  1963.0
12156   UA       44796964.0               NaN  1964.0
12157   UA       45264548.0               NaN  1965.0
12158   UA       45684979.0               NaN  1966.0
12159   UA       46063228.0               NaN  1967.0
12160   UA       46411810.0               NaN  1968.0
12161   UA       46749283.0               NaN  1969.0
12162   UA       47088857.0               NaN  1970.0
12163   UA       47435010.0               NaN  1971.0
12164   UA       47783005.0               NaN  1972.0
12165   UA       48125842.0               NaN  1973.0
12166   UA       48452626.0               NaN  1974.0
12167   UA       48755665.0               NaN  1975.0
12168   UA       49032729.0               NaN  1976.0
12169   UA       49287127.0               NaN  1977.0
12170   UA       49523314.0               NaN  1978.0
12171   UA       49747989.0               NaN  1979.0
12172   UA       49965874.0               NaN  1980.0
12173   UA       50221000.0               NaN  1981.0
12174   UA       50384000.0               NaN  1982.0
12175   UA       50564000.0               NaN  1983.0
12176   UA       50754000.0               NaN  1984.0
12177   UA       50917000.0               NaN  1985.0
12178   UA       51097000.0               NaN  1986.0
12179   UA       51293000.0               NaN  1987.0
12180   UA       51521000.0               NaN  1988.0
12181   UA       51773000.0               NaN  1989.0
12182   UA       51891400.0               NaN  1990.0
12183   UA       52000500.0               NaN  1991.0
12184   UA       52150400.0        35558040.0  1992.0
12185   UA       52179200.0        42732798.0  1993.0
12186   UA       51921400.0        32860971.0  1994.0
12187   UA       51512800.0        32360000.0  1995.0
12188   UA       51057800.0        23449056.0  1996.0
12189   UA       50594600.0        34394720.0  1997.0
12190   UA       50144500.0        25699039.0  1998.0
12191   UA       49674000.0        23960469.0  1999.0
12192   UA       49176500.0        23814124.0  2000.0
12193   UA       48662400.0        38886120.0  2001.0
12194   UA       48202470.0        37984706.0  2002.0
12195   UA       47812949.0        27493984.0  2003.0
12196   UA       47451626.0        40996700.0  2004.0
12197   UA       47105171.0        37258000.0  2005.0
12198   UA       46787786.0        33518622.0  2006.0
12199   UA       46509355.0        28945258.0  2007.0
12200   UA       46258189.0        52747334.0  2008.0
12201   UA       46053331.0        45413410.0  2009.0
12202   UA       45870741.0        38685987.0  2010.0
12203   UA       45706086.0        56263263.0  2011.0
12204   UA       45593342.0        45750171.0  2012.0
12205   UA       45489648.0        62687582.0  2013.0
12206   UA       45272155.0        63388560.0  2014.0
12207   UA       45154036.0        59627180.0  2015.0
12208   UA       45004673.0        65217850.0  2016.0
12209   UA       44831135.0        60685735.0  2017.0
12210   UA       44622518.0        69109347.0  2018.0
12211   UA       44386203.0               NaN  2019.0

In [63]:
# 4
Ukrainian = Ukrainian.rename({"time": "year"}, axis = 1)
Ukrainian

iso2  totalPopulation  cerealProduction    year
12152   UA       42664652.0               NaN  1960.0
12153   UA       43206345.0               NaN  1961.0
12154   UA       43752230.0               NaN  1962.0
12155   UA       44288608.0               NaN  1963.0
12156   UA       44796964.0               NaN  1964.0
12157   UA       45264548.0               NaN  1965.0
12158   UA       45684979.0               NaN  1966.0
12159   UA       46063228.0               NaN  1967.0
12160   UA       46411810.0               NaN  1968.0
12161   UA       46749283.0               NaN  1969.0
12162   UA       47088857.0               NaN  1970.0
12163   UA       47435010.0               NaN  1971.0
12164   UA       47783005.0               NaN  1972.0
12165   UA       48125842.0               NaN  1973.0
12166   UA       48452626.0               NaN  1974.0
12167   UA       48755665.0               NaN  1975.0
12168   UA       49032729.0               NaN  1976.0
12169   UA       49287127.0               NaN  1977.0
12170   UA       49523314.0               NaN  1978.0
12171   UA       49747989.0               NaN  1979.0
12172   UA       49965874.0               NaN  1980.0
12173   UA       50221000.0               NaN  1981.0
12174   UA       50384000.0               NaN  1982.0
12175   UA       50564000.0               NaN  1983.0
12176   UA       50754000.0               NaN  1984.0
12177   UA       50917000.0               NaN  1985.0
12178   UA       51097000.0               NaN  1986.0
12179   UA       51293000.0               NaN  1987.0
12180   UA       51521000.0               NaN  1988.0
12181   UA       51773000.0               NaN  1989.0
12182   UA       51891400.0               NaN  1990.0
12183   UA       52000500.0               NaN  1991.0
12184   UA       52150400.0        35558040.0  1992.0
12185   UA       52179200.0        42732798.0  1993.0
12186   UA       51921400.0        32860971.0  1994.0
12187   UA       51512800.0        32360000.0  1995.0
12188   UA       51057800.0        23449056.0  1996.0
12189   UA       50594600.0        34394720.0  1997.0
12190   UA       50144500.0        25699039.0  1998.0
12191   UA       49674000.0        23960469.0  1999.0
12192   UA       49176500.0        23814124.0  2000.0
12193   UA       48662400.0        38886120.0  2001.0
12194   UA       48202470.0        37984706.0  2002.0
12195   UA       47812949.0        27493984.0  2003.0
12196   UA       47451626.0        40996700.0  2004.0
12197   UA       47105171.0        37258000.0  2005.0
12198   UA       46787786.0        33518622.0  2006.0
12199   UA       46509355.0        28945258.0  2007.0
12200   UA       46258189.0        52747334.0  2008.0
12201   UA       46053331.0        45413410.0  2009.0
12202   UA       45870741.0        38685987.0  2010.0
12203   UA       45706086.0        56263263.0  2011.0
12204   UA       45593342.0        45750171.0  2012.0
12205   UA       45489648.0        62687582.0  2013.0
12206   UA       45272155.0        63388560.0  2014.0
12207   UA       45154036.0        59627180.0  2015.0
12208   UA       45004673.0        65217850.0  2016.0
12209   UA       44831135.0        60685735.0  2017.0
12210   UA       44622518.0        69109347.0  2018.0
12211   UA       44386203.0               NaN  2019.0